export default function CandlesCare() {
  return (
    <>
     <div className="bg-white font-serif min-h-screen shadow">
          <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
            <h1 className="text-3xl  border-b mt-20 font-bold tracking-tight text-gray-900">Péče o svíčky</h1>
            <p className="mt-5 flex justify-center">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Cras elementum. Phasellus faucibus molestie nisl. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Integer pellentesque quam vel velit. Suspendisse nisl. Nullam rhoncus aliquam metus. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Et harum quidem rerum facilis est et expedita distinctio. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Nulla non lectus sed nisl molestie malesuada. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Nullam rhoncus aliquam metus. Suspendisse sagittis ultrices augue. Vivamus ac leo pretium faucibus. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Donec iaculis gravida nulla. Sed convallis magna eu sem. Nullam sit amet magna in magna gravida vehicula.</p>
              <p className="mt-5 flex justify-center">Nullam at arcu a est sollicitudin euismod. Sed convallis magna eu sem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Etiam bibendum elit eget erat. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Nulla est. Nunc tincidunt ante vitae massa. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Nullam eget nisl. Phasellus rhoncus. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Aliquam erat volutpat. Aenean vel massa quis mauris vehicula lacinia. Aliquam ante. Aenean fermentum risus id tortor. Nulla est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam sed tellus id magna elementum tincidunt. Donec vitae arcu.</p>
              <p className="mt-5 flex justify-center">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Integer pellentesque quam vel velit. Curabitur sagittis hendrerit ante. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Etiam bibendum elit eget erat. Pellentesque pretium lectus id turpis. Integer imperdiet lectus quis justo. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Quisque porta. Vestibulum fermentum tortor id mi. Quisque tincidunt scelerisque libero. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Duis condimentum augue id magna semper rutrum. Etiam posuere lacus quis dolor. Nulla est. Quisque porta. Curabitur bibendum justo non orci.</p>
              <p className="mt-5 flex justify-center">Cras elementum. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc tincidunt ante vitae massa. Cras elementum. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris dictum facilisis augue. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Nullam at arcu a est sollicitudin euismod. In sem justo, commodo ut, suscipit at, pharetra vitae, orci. Etiam bibendum elit eget erat.</p>
              <p className="mt-5 flex justify-center">Nullam rhoncus aliquam metus. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Pellentesque sapien. Maecenas sollicitudin. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Mauris metus. Duis risus. Fusce aliquam vestibulum ipsum. Nam sed tellus id magna elementum tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla non arcu lacinia neque faucibus fringilla. Integer tempor. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Nullam faucibus mi quis velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          </div>
        </div>
        <div className="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8"></div>
    </>
  )
}
